### PR TITLE
 Integration of NanoDet Model

### PR DESCRIPTION
**Pull request by deshpandeneeraj**
This PR introduces the integration of the NanoDet object detection model into the Sahi library.

Key Changes:

**Addition of NanoDet Model**: The NanoDet model has been added to the existing model library. This allows users to utilize NanoDet for object detection tasks, expanding Sahi's capabilities to include lightweight and efficient detection models.
Model Configuration and Weights: The necessary configuration files and pre-trained weights for the NanoDet model have been included. These configurations ensure optimal performance of the model within the Sahi environment.

**Unit Tests**: Unit tests have been added to ensure the correct functionality of the NanoDet model. These tests cover various scenarios to ensure robustness.

**Cleanup** :- Black, ISort, and Ruff has been run until no errors remain. Only a few Line too long for docstrings.

This integration broadens the range of models that Sahi supports, enabling users to leverage the NanoDet model's benefits, especially in scenarios where efficiency and model size are key considerations.

Please review the changes and provide any necessary feedback.

### CODE REVIEW

**Comment by deshpandeneeraj** [comment]
@fcakyon could you review this if you have the time?

**Comment by fcakyon** [comment]
Thanks for your great contribution @deshpandeneeraj !

If you could add some tests and a demo notebook as other model implementations, we would gladly accept this PR 👍

**Review by fcakyon — CHANGES_REQUESTED** [review]
tests and a demo notebook need to be added

**Comment by deshpandeneeraj** [comment]
Yes will do

**Pull request closed without merging**
