### PR TITLE
Finally, the working version of YoloV8 Instance Segmentation

### PR DESCRIPTION
**Pull request by sweetlhare**
Redid the previous pull request. Conducted testing.

### CODE REVIEW

**Comment by sweetlhare** [comment]
Test slice/no slice with detection model on image without objects and on image with objects.

clear_blue_sky png
sliced_clear_blue_sky png
sliced_small-vehicles1 jpeg
small-vehicles1 jpeg

**Comment by sweetlhare** [comment]
Test slice/no slice with Instance Segmentation model on image without objects and on image with objects.

clear_blue_sky-seg png
sliced_clear_blue_sky-seg png
sliced_small-vehicles1-seg jpeg
small-vehicles1-seg jpeg

**Comment by sweetlhare** [comment]
The interface is identical to the detection model

`from sahi.sahi import AutoDetectionModel
from sahi.sahi.predict import get_prediction, get_sliced_prediction

detection_model = AutoDetectionModel.from_pretrained(
    model_type='yolov8',
    model_path='yolov8n-seg.pt',
    confidence_threshold=0.5,
    device='cuda:0' # if torch.cuda.is_available() else 'cpu'
)

pred = get_sliced_prediction('small-vehicles1.jpeg', detection_model, 
                            slice_height=640, slice_width=640, 
                            overlap_height_ratio=0.4, overlap_width_ratio=0.4)

pred.export_visuals('test_results/', file_name='sliced_small-vehicles1-seg.jpeg')`

**Comment by Aprilistic** [comment]
Thank you for updating!! I managed to use yolov8 seg model to sahi. However, you missed threshold_confidence.

<Original>
            prediction_result_ = [(result.boxes.data[result.boxes.data[:, 4] >= 0.5], 
                                   result.masks.data[result.boxes.data[:, 4] >= 0.5]) 
                                   for result in prediction_result]
                                   
<Modified>                                   
            prediction_result_ = [(result.boxes.data[result.boxes.data[:, 4] >= self.confidence_threshold], 
                                  result.masks.data[result.boxes.data[:, 4] >= self.confidence_threshold]) 
                                  for result in prediction_result]          
                                                     
                                                     
This code worked well.

**Review by Aprilistic — CHANGES_REQUESTED** [review]
Thank you for updating!! I managed to use yolov8 seg model to sahi. However, you missed threshold_confidence. At line 72, 73

Original, Line 72, 73
            prediction_result_ = [(result.boxes.data[result.boxes.data[:, 4] >= 0.5], 
                                  result.masks.data[result.boxes.data[:, 4] >= 0.5]) 
                                  for result in prediction_result]

Modified
            prediction_result_ = [(result.boxes.data[result.boxes.data[:, 4] >= self.confidence_threshold], 
                                  result.masks.data[result.boxes.data[:, 4] >= self.confidence_threshold]) 
                                  for result in prediction_result]

This code worked well.

**Comment by sweetlhare** [comment]
Thanks a lot! I set a fixed trash hold for local tests, forgot to change it back

**Comment by Jareco** [comment]
Probably I did something wrong, but I still have the following error:

```
File "C:\Projects\levasoft\SolarProTool-ObjectDetector\app\handlers\yolohandler.py", line 33, in predict
    result = get_sliced_prediction(
  File "C:\Projects\levasoft\SolarProTool-ObjectDetector\app\sahi\predict.py", line 261, in get_sliced_prediction
    prediction_result = get_prediction(
  File "C:\Projects\levasoft\SolarProTool-ObjectDetector\app\sahi\predict.py", line 100, in get_prediction
    detection_model.convert_original_predictions(
  File "C:\Projects\levasoft\SolarProTool-ObjectDetector\app\sahi\models\base.py", line 168, in convert_original_predictions
    self._create_object_prediction_list_from_original_predictions(
  File "C:\Projects\levasoft\SolarProTool-ObjectDetector\app\sahi\models\yolov8.py", line 182, in _create_object_prediction_list_from_original_predictions
    object_prediction = ObjectPrediction(
  File "C:\Projects\levasoft\SolarProTool-ObjectDetector\app\sahi\prediction.py", line 75, in __init__
    super().__init__(
  File "C:\Projects\levasoft\SolarProTool-ObjectDetector\app\sahi\annotation.py", line 581, in __init__
    raise ValueError("Invalid boolean mask.")
ValueError: Invalid boolean mask.
```

I use the following code:

        detection_model = AutoDetectionModel.from_pretrained(
            model_type='yolov8',
            model_path=config.YOLOMODEL_PATH,
            confidence_threshold=0.3,
            device="cpu", # or 'cuda:0'
        )

        result = get_sliced_prediction(
            "C:\\GRoof_22037481-dc2c-43d4-aab6-238d5f254bd6.png",
            detection_model,
            slice_height = 256,
            slice_width = 256,
            overlap_height_ratio = 0.2,
            overlap_width_ratio = 0.2
        )
        
Here is the picture:
https://imgur.com/a/GtcGS2Y

I detect obstacles on the roof, but somehow I get an error with invalid boolean mask. I also had this error with previous pull request.

**Comment by sweetlhare** [comment]
I checked on your image and with your parameters, everything works. To get some detection results, I added an object to the image
sliced_ZzvCGl1-seg jpeg

**Comment by sweetlhare** [comment]
I will check what the problem may be asap

**Comment by rezat96** [comment]
Hey @sweetlhare, is there any update on this?
thanks

**Comment by OscarPetersen1992** [comment]
Any update on this?

**Comment by FourierMourier** [comment]
Any updates? masks are correct and it works fine

**Comment by CyVision13** [comment]
Thanks a lot, can you update please? @sweetlhare

**Comment by jehanjen** [comment]
> Thank you for updating!! I managed to use yolov8 seg model to sahi. However, you missed threshold_confidence. At line 72, 73
> 
> Original, Line 72, 73 prediction_result_ = [(result.boxes.data[result.boxes.data[:, 4] >= 0.5], result.masks.data[result.boxes.data[:, 4] >= 0.5]) for result in prediction_result]
> 
> Modified prediction_result_ = [(result.boxes.data[result.boxes.data[:, 4] >= self.confidence_threshold], result.masks.data[result.boxes.data[:, 4] >= self.confidence_threshold]) for result in prediction_result]
> 
> This code worked well.
could you please the segment code with sahi

**Comment by jehanjen** [comment]
> Is this implemented in the main branch? I can't see the yolov8 segmentation model there

the same for me

**Comment by jehanjen** [comment]
> I checked on your image and with your parameters, everything works. To get some detection results, I added an object to the image sliced_ZzvCGl1-seg jpeg

could you please share the cml for segmntation with sahi ans the code please

**Comment by jehanjen** [comment]
> The interface is identical to the detection model
> 
> `from sahi.sahi import AutoDetectionModel from sahi.sahi.predict import get_prediction, get_sliced_prediction
> 
> detection_model = AutoDetectionModel.from_pretrained( model_type='yolov8', model_path='yolov8n-seg.pt', confidence_threshold=0.5, device='cuda:0' # if torch.cuda.is_available() else 'cpu' )
> 
> pred = get_sliced_prediction('small-vehicles1.jpeg', detection_model, slice_height=640, slice_width=640, overlap_height_ratio=0.4, overlap_width_ratio=0.4)
> 
> pred.export_visuals('test_results/', file_name='sliced_small-vehicles1-seg.jpeg')`

which code you have been used for segmentation with sahi?

**Comment by libazhahei** [comment]
I also wrote similar code to yours, but I found that the memory usage was very very high..

**Comment by jehanjen** [comment]
Ouod you please write which code you have been using

**Comment by sweetlhare** [comment]
Hello everyone! 
In this version, segmentation should work fine, but there is really a lot of memory consumption with a large number of masks. The problem comes from the original logic of SAHI's work. Now, within our development team, we have made a simplified and optimized version, as soon as we finalize it for SAHI, we will update the pull request.

**Comment by alexkutsan** [comment]
I am also verry interested in YOLOv8 segmentation with SAHI.

Tried version from 
```
pip install git+https://github.com/sweetlhare/sahi-yolov8-instance-segmentation.git@main
```
It processes several images and then throw an exception.
```
Traceback (most recent call last):
  File "/home/alex/rnd/company/tracks_tools/./segment_compare.py", line 75, in <module>
    check_detector("yolov8_sahi", yolo8_sahi_detector,
  File "/home/alex/rnd/company/tracks_tools/./segment_compare.py", line 54, in check_detector
    result = detect_func(image)
  File "/home/alex/rnd/company/tracks_tools/adssai/tracks_extraction/detectors.py", line 73, in __call__
    results = get_prediction(image, self.model)
  File "/home/alex/rnd/company/tracks_tools/venv/lib/python3.10/site-packages/sahi/predict.py", line 100, in get_prediction
    detection_model.convert_original_predictions(
  File "/home/alex/rnd/company/tracks_tools/venv/lib/python3.10/site-packages/sahi/models/base.py", line 168, in convert_original_predictions
    self._create_object_prediction_list_from_original_predictions(
  File "/home/alex/rnd/company/tracks_tools/venv/lib/python3.10/site-packages/sahi/models/yolov8.py", line 182, in _create_object_prediction_list_from_original_predictions
    object_prediction = ObjectPrediction(
  File "/home/alex/rnd/company/tracks_tools/venv/lib/python3.10/site-packages/sahi/prediction.py", line 75, in __init__
    super().__init__(
  File "/home/alex/rnd/company/tracks_tools/venv/lib/python3.10/site-packages/sahi/annotation.py", line 581, in __init__
    raise ValueError("Invalid boolean mask.")
ValueError: Invalid boolean mask.
```
Let me know if you need more info or more context.
i attached the video file that I am processing. 

https://github.com/obss/sahi/assets/860357/4dc24d4f-c62f-4b10-9372-5f79bd02e30d

**Comment by jehanjen** [comment]
> Hello everyone! In this version, segmentation should work fine, but there is really a lot of memory consumption with a large number of masks. The problem comes from the original logic of SAHI's work. Now, within our development team, we have made a simplified and optimized version, as soon as we finalize it for SAHI, we will update the pull request.

sahi segmentation with coco format??? can i use just the image to segment with sahi?

**Comment by fcakyon** [comment]
> Hello everyone! In this version, segmentation should work fine, but there is really a lot of memory consumption with a large number of masks. The problem comes from the original logic of SAHI's work. Now, within our development team, we have made a simplified and optimized version, as soon as we finalize it for SAHI, we will update the pull request.

Wow amazing to hear that!

Feel free to ping me once PR is ready so that I can merge it 👍

**Review by fcakyon — CHANGES_REQUESTED** [review]
yolov8 demo notebook should be updated with a segmentation example, failing tests need to be handled

**Comment by theoden8** [comment]
I've ran this, and I'm getting a lot of overlapping masks in return that aren't combined together - is that expected?

**Comment by AntonioRodriguezRuiz** [comment]
Hi! Is there any updates on this?

**Comment by fcakyon** [comment]
> Hi! Is there any updates on this?

We need @sweetlhare's cooperation to make this PR ready (fixing tests and adding/updating a demo notebook)

**Comment by gfx73** [comment]
Hi!
Up to my understanding the feature implemented here uses segmentation model to perfrorm detection. Am I right? I tried this code snippet and ```pred``` value's dictionary has Nones for masks.

> The interface is identical to the detection model
> 
> `from sahi.sahi import AutoDetectionModel from sahi.sahi.predict import get_prediction, get_sliced_prediction
> 
> detection_model = AutoDetectionModel.from_pretrained( model_type='yolov8', model_path='yolov8n-seg.pt', confidence_threshold=0.5, device='cuda:0' # if torch.cuda.is_available() else 'cpu' )
> 
> pred = get_sliced_prediction('small-vehicles1.jpeg', detection_model, slice_height=640, slice_width=640, overlap_height_ratio=0.4, overlap_width_ratio=0.4)
> 
> pred.export_visuals('test_results/', file_name='sliced_small-vehicles1-seg.jpeg')`

image

**Comment by dimka11** [comment]
How to fix ValueError: Invalid boolean mask?

**Comment by AndrewArchie** [comment]
I was wondering if there will be a similar update for using segmentation for YoloV5? Thanks a lot!

**Comment by ozayr** [comment]
Hi, how would I get the actual polygon of the segmented area, currently only the mask seems to be available. Is this something that is there, or is it not implemented ?

**Comment by FilipeMendesVMD** [comment]
Does anyone has a colab notebook for this solution? I am trying to replicate but no success... :(

**Comment by jehanjen** [comment]
> Hi, how would I get the actual polygon of the segmented area, currently only the mask seems to be available. Is this something that is there, or is it not implemented ?

i also need SAHI with segmentation for polygon ?

**Comment by fmandel98** [comment]
I included the provided code for segmentation and it works partially. Unfortunately is the bounding box prediction worse than before. It seems it is wrongly shifted. Someone has the same issue?

**Comment by kyra-smith** [comment]
> Hi! Up to my understanding the feature implemented here uses segmentation model to perfrorm detection. Am I right? I tried this code snippet and `pred` value's dictionary has Nones for masks.
> 
> > The interface is identical to the detection model
> > `from sahi.sahi import AutoDetectionModel from sahi.sahi.predict import get_prediction, get_sliced_prediction
> > detection_model = AutoDetectionModel.from_pretrained( model_type='yolov8', model_path='yolov8n-seg.pt', confidence_threshold=0.5, device='cuda:0' # if torch.cuda.is_available() else 'cpu' )
> > pred = get_sliced_prediction('small-vehicles1.jpeg', detection_model, slice_height=640, slice_width=640, overlap_height_ratio=0.4, overlap_width_ratio=0.4)
> > pred.export_visuals('test_results/', file_name='sliced_small-vehicles1-seg.jpeg')`
> 
> image

I'm having the same issue.

**Comment by fcakyon** [comment]
closing the PR in favor of https://github.com/obss/sahi/pull/1039

**Pull request closed without merging**
