### PR TITLE
Fix bug that Unable to print for prediction time when verbose=2

### PR DESCRIPTION
**Pull request by youngjae-avikus**
Error executing below in current code
 
```python
result = get_sliced_prediction(
    "demo_data/small-vehicles1.jpeg",
    detection_model,
    slice_height = 256,
    slice_width = 256,
    overlap_height_ratio = 0.2,
    overlap_width_ratio = 0.2,
    verbose=2
)
```

### CODE REVIEW

**Comment by fcakyon** [comment]
@youngjae-avikus thanks a lot for catching it!

**Comment by fcakyon** [comment]
Can you please reformat your code with:

```bash
pip install -e ."[dev]"
black . --config pyproject.toml
isort .
```

**Comment by youngjae-avikus** [comment]
@fcakyon 
I modified it

**Comment by youngjae-avikus** [comment]
@fcakyon 

There is a build error due to the connection error, is it a network problem?

**Comment by fcakyon** [comment]
@youngjae-avikus that connection error is not related to us, thanks a lot for your contribution!

**Pull request merged**
