### PR TITLE
add lsnms postprocess

### PR DESCRIPTION
**Pull request by fcakyon**
solves: https://github.com/obss/sahi/issues/263

based on: https://github.com/remydubois/lsnms

### CODE REVIEW

**Comment by fcakyon** [comment]
Can you please check if my implementation is correct? :) @remydubois @phborba

**Comment by remydubois** [comment]
Hey, I think everything is correct for the `nms` part 🎉 

However, weighted box clustering (`wbc`) returns a new set of boxes and scores (because it "creates" instances that did not exist in the input list: by averaging boxes and scores cluster-wise).  
I think it would look like something like this:
```python3
boxes, scores, _ = wbc(boxes, scores, self.match_threshold)
```
Having said that, I am not really sure how WBC should be applied in a multi class setting: if a car and a horse overlap, it does not make much sense to me to aggregate them together... what do you think @fcakyon ?
(note that the problem does not arise with NMS since we just discard the lowest scoring one).

**Comment by fcakyon** [comment]
You are right integrating wbc into sahi is not trivial. Will remove it for now 👍

**Comment by remydubois** [comment]
okay :) LGTM then

**Comment by fcakyon** [comment]
@remydubois i have one last question. Current implementation applies class agnostic nms, right? (so it can combine predictions from different categories)

**Comment by remydubois** [comment]
@fcakyon  Absolutely, it is completely class agnostic. If a multi class NMS seems useful to you I could try and see how to integrate it while keeping performance level high.

On a different topic: I know that at first use, NMS can lag a bit (10-15 seconds), which is due to Numba's inner compiling of recursive functions. I know that they have been trying to solve the issue ([cf this issue](https://github.com/numba/numba/issues/6713#issue-804901574)) but it is still pending as of now.  
I will update `lsnms` as soon as this is fixed (hopefully it will one day).

**Comment by fcakyon** [comment]
> @fcakyon Absolutely, it is completely class agnostic. If a multi class NMS seems useful to you I could try and see how to integrate it while keeping performance level high.

High performance multi class NMS implementation would be awesome!

**Comment by remydubois** [comment]
I will release it version 0.3.0 soon, the api should change a little bit so perhaps wait that i release it, and adapt this branch before merging it
(Should just be an extra argument ´class_ids’ to lsnms.nms)

**Comment by fcakyon** [comment]
Awesome news @remydubois!

**Comment by remydubois** [comment]
@fcakyon `lsnms` version 0.3.X should be published on pypi and handle the multiclass setting, with a minimal modification of the API.

**Comment by fcakyon** [comment]
@remydubois i am trying to add lsnms support with the next release but having this error when testing: 

```
Exception has occurred: ValueError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
Class ids should be a positive integer array. Received float32 with min 0.0
  File "/home/xxx/miniconda3/envs/xxx/lib/python3.8/site-packages/lsnms/util.py", line 421, in check_correct_arrays
    raise ValueError(
  File "/home/xxx/miniconda3/envs/xxx/lib/python3.8/site-packages/lsnms/util.py", line 465, in check_correct_input
    check_correct_arrays(boxes, scores, class_ids)
  File "/home/xxx/miniconda3/envs/xxx/lib/python3.8/site-packages/lsnms/nms.py", line 144, in nms
    boxes, scores, class_ids = check_correct_input(
```

In most of the datasets class ids are starting from 0 so i cannot change the class ids..

**Comment by remydubois** [comment]
Hey,
I think the error is fired because you provided class ids as a floating point vector.
The underlying code uses np.can_cast, so if the error is fired, it means the class_ids can not be casted to integer.

Try converting it to integer on your side (or ensure that all the values provided are, at least, round floats).

**Comment by fcakyon** [comment]
@remydubois thanks a lot for the feedback! Will try to cast them to int before calling lsnms 👍

**Pull request closed without merging**
